# ============================================================
# RETAIL STORE - PRODUCTION VALUES
# Environment: AWS EKS Production
# ============================================================


# ============================================================
# GLOBAL CONFIGURATION
# ============================================================

global:
  environment: prod


# ============================================================
# DYNAMODB SERVICE
# ============================================================
# Local/in-cluster DynamoDB is disabled in production.
# Cart uses AWS DynamoDB in ap-south-1 instead.

retail-store-dynamodb:
  enabled: false


# ============================================================
# CART SERVICE
# ============================================================

retail-store-cart:

  image:
    repository: ahmad2001/retail-store-cart
    tag: v2

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi

  # Production authentication method:
  # IRSA = IAM Roles for Service Accounts
  # No static AWS access keys are stored inside the Pod.
  aws:
    authMethod: irsa

  serviceAccount:
    create: true
    name: cart-sa
    roleArn: arn:aws:iam::118051225085:role/cart-dynamodb-role


# ============================================================
# CATALOG SERVICE
# ============================================================

retail-store-catalog:

  image:
    repository: ahmad2001/retail-store-catalog
    tag: v2

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi


# ============================================================
# CHECKOUT SERVICE
# ============================================================

retail-store-checkout:

  image:
    repository: ahmad2001/retail-store-checkout
    tag: v2

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi


# ============================================================
# ORDERS SERVICE
# ============================================================

retail-store-orders:

  image:
    repository: ahmad2001/retail-store-orders
    tag: v2

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi


# ============================================================
# UI SERVICE
# ============================================================

retail-store-ui:

  image:
    repository: ahmad2001/retail-store-ui
    tag: v2

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
